### ISSUE TITLE
Putting on discord?

### ISSUE THREAD

**Issue by ksogoltsov** [Lyceion/ButOSX#16]
Is it okay if we upload it on discord to the public(we will include a link to your GitHub profile, we will just keep the daily builds and beta commits that you made and upload it on our discord for people) can we do it?

**Comment by ksogoltsov** [comment]
by daily build I mean every time you commit something, we upload it on discord

**Comment by Lyceion** [comment]
It's okey. I only care about credits. There's bo problem.

**Comment by ksogoltsov** [comment]
Thank you so much!
