### ISSUE TITLE
why is it crashing when i inject?

### ISSUE THREAD

**Issue by yash-blip** [Lyceion/ButOSX#17]
whenever i inject it crashed i builded the main

**Comment by Lyceion** [comment]
Can you attach debugger and show me the error?

**Comment by Lyceion** [comment]
> whenever i inject it crashed i builded the main

Also can you write your system spesifications?

**Comment by yash-blip** [comment]
> > whenever i inject it crashed i builded the main
> 
> Also can you write your system spesifications?

i5 8gb ram and i used the one that u have sent in main. macos catalina

**Comment by Lyceion** [comment]
> > > whenever i inject it crashed i builded the main
> > 
> > 
> > Also can you write your system spesifications?
> 
> i5 8gb ram and i used the one that u have sent in main. macos catalina

Sorry i don't understand. Did you compiled yourself or just downloaded the one which is in releases section?

**Comment by yash-blip** [comment]
i just downloaded the precompiled one

**Comment by Lyceion** [comment]
> i just downloaded the precompiled one
> 
> 

Weird. What's rhe exactly version of macos you want? I mean 10.15 or what?

**Comment by yash-blip** [comment]
10.15.7 oh i see i had to use osxinj can u pls provide that injector

**Comment by Lyceion** [comment]
> 10.15.7 oh i see i had to use osxinj can u pls provide that injector

Osxinj doesn't belong to me so i can't provide officialy (at least for now). You can download and compile from https://github.com/scen/osxinj . But i'm planning to create an injector with official support.

Note: If you have another injector, it's supported to. But as i know there's only one dylib injector for macosx (atm).

**Comment by yash-blip** [comment]
> > 10.15.7 oh i see i had to use osxinj can u pls provide that injector
> 
> Osxinj doesn't belong to me so i can't provide officialy (at least for now). You can download and compile from https://github.com/scen/osxinj . But i'm planning to create an injector with official support.
> 
> Note: If you have another injector, it's supported to. But as i know there's only one dylib injector for macosx (atm).

i used the normal injector which is available with the rest cheats of mac. like what all is need ted to be in the file when i sudo the file and comands?

**Comment by Lyceion** [comment]
Can you link your injector? And for the osxinj, put the bootstrap.dylib, libButOSX.dylib and osxinj with the same folder. And use the command 'sudo ./osxinj csgo_osx64 libButOSX.dylib' 

Note: change libButOSX.dylib to which dylib you want to inject.

As i said before, can you link the other injector you use? And where did you find it?

**Comment by Lyceion** [comment]
#18 Fixed on it.
