### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by cristeigabriel** [Lyceion/ButOSX#19]
https://github.com/Lyceion/ButOSX/blob/c9c5960c07cc4feb72fff9eadb7b0f9cac86a363/ButOSX/SDK/Hooks/GameHooker/GameHooker.cpp#L82

this is (probably) going to be managed by the system's internals, but you'd ideally want to use smart pointers for this situation, or just handle the allocations by hand.

**Comment by Lyceion** [comment]
Pointers shouldn't be destroyed. Calling them everytime when i call method original. If when i call https://github.com/Lyceion/ButOSX/blob/beta/ButOSX/SDK/Hooks/GameHooker/GameHooker.cpp#L39 it'll wont work because smart pointer's gonna destroy when function is finished. And you can't unload the cheat because of some macos problems so you should restart the game for inject again so pointer's are not really a problem. Also i think apple's optimizers can manage them.

**Comment by cristeigabriel** [comment]
I see, excuse me for not looking into it first hand. Furthermore, my worry came from the fact that this would be an 'unsafe' optimization, wouldn't it? But then again behaviour would be replicated by the MacOS internals handling the still-remaining allocated memory of the process when killed. 

To further clarify, my idea is that having an unique pointer in that situation shouldn't limit lifetime to scope due to storage, right?

Also, I alternatively do this for setting VMT.

```
    //  +1s for rtti
    template<typename T, size_t N>
    void hook()
    {
        static_assert(N > 0);
        assert(N < m_table_size);
        m_replacement_table.get()[N + 1] = (DWORD)T::hooked;
        T::original = (decltype(T::original))(m_original_table[N]);
    }

#define PROTOTYPE_FUNCTION(function_name, function_prototype)                                                                              \
    struct function_name                                                                                                                   \
    {                                                                                                                                      \
        using fn = function_prototype;                                                                                                     \
        static fn  hooked;                                                                                                                 \
        static fn* original;                                                                                                               \
    };                                                                                                                                     \
    inline function_name::fn* function_name::original;
```

**Comment by Lyceion** [comment]
Oh, i see. Thanks for the info btw. Noted but i'm gonna do the optimization things last. BTW tested it and it seems like only place i have the memory leak is the PatterScanner initializer.
https://github.com/Lyceion/ButOSX/blob/c9c5960c07cc4feb72fff9eadb7b0f9cac86a363/ButOSX/SDK/Classes/Utilities/PatternScanner.hpp#L32

BTW, i'm not an C or C++ expert. I'm trying my best and again, thanks for help...

**Comment by cristeigabriel** [comment]
Sure thing, me neither, and it's all fine

Also, for that, you should be able to simply delete _instance in destructor which'll be called on atexit().

Also, I made a cool thing-y that u might find interesting for pattern scanners, as you mentioned them, [shameless plug](https://github.com/cristeigabriel/compiletime-string-to-bytearray) [although it's not exactly needed for your situation but when applied it can simplify the scanning code a lot in the end)
