### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ALoZo1** [Lyceion/ButOSX#5]
how open menu and inject?

**Comment by Lyceion** [comment]
Inject with [OSXINJ](https://github.com/scen/osxinj) . You can open menu with "insert" or touchbar key.

**Comment by Lyceion** [comment]
Ok, no response. Than, closing it...

**Comment by ALoZo1** [comment]
Injection error

module: 0xFF500000
bootstrapfn: 0xAD32D90
pid: 99174
image name: /Users/alonzo/Downloads/buteosx/bootstrap.dylib
mach_inject: found threadEntry image at: 0x10ad32000 with size: 28400
wrote param with size 44

**Comment by Lyceion** [comment]
#6 Talked on here.
