### ISSUE TITLE
How to use osxinj?

### ISSUE THREAD

**Issue by ALoZo1** [Lyceion/ButOSX#6]
Injection error
osxinj : 

module: 0xFF500000
bootstrapfn: 0xAD32D90
pid: 99174
image name: /Users/alonzo/Downloads/buteosx/bootstrap.dylib
mach_inject: found threadEntry image at: 0x10ad32000 with size: 28400
wrote param with size 44

**Comment by Lyceion** [comment]
Ok, mate. Put the osxinj within bootstrap (same folder i mean). Than send that command to terminal:
`sudo ./osxinj csgo_osx64 libButOSX.dylib`.

I'm going to upload compiled library within 1-2 minutes. Check it out...

**Comment by ALoZo1** [comment]
ok and where will you upload bootstrap

**Comment by Lyceion** [comment]
Bootstrap is osxinj's thing. It doesn't concern me. I only uploaded the ButOSX.
Note: I don't take any responsibilites about using it. Use at your own risk...
