### ISSUE TITLE
Injection Failing on M1 Macbook

### ISSUE THREAD

**Issue by jakepriddle** [Lyceion/ButOSX#8]
The following error occurs when injecting on a M1 MacBook Pro running big Sur:
<img width="537" alt="Screen Shot 2021-02-02 at 12 55 22 PM" src="https://user-images.githubusercontent.com/50683048/106642070-eabfdc80-6555-11eb-9b1d-6360cdd11bed.png">
The injector works fine on other programs which would make me believe that it is a problem with the cheat. I am sorry for causing any problems, I don't have much knowledge with c++.\
Any solution would be greatly appreciated.

**Comment by Lyceion** [comment]
1- First of all, we don't have M1 MacBook Pro. It's probably about compilation arguments. The one which in releases, compiled for x86_64. You should compile for your M1 system. 

2- Compile OSXInj & Bootstrap for your M1. They have diffrent arch. 
(Sorry for my english btw)

(If OSXInj works for another dylibs, make 1. one)

Btw, i'm gonna make an injector from scratch.

**Comment by jakepriddle** [comment]
Yah I did, what is weird is that the m1 macs have Rosetta, a program that lets them emulate x86_64 programs, I’ll be excited to try in the future with your new injector to see if it works any better.

**Comment by Lyceion** [comment]
So, is it working right now? I mean can you see the menu?
Key is insert or you can just use the touchbar button...

I'm asking because i'm gonne close the issue if it is worked...

**Comment by Lyceion** [comment]
You should download the project and compile for your M1 for smoother experience and fix the error.

**Comment by jakepriddle** [comment]
I did that, it still gives the same error, very weird.

**Comment by jakepriddle** [comment]
[osxinj.zip](https://github.com/Lyceion/ButOSX/files/5922321/osxinj.zip)
tell me if this works,
compiled on my machine

**Comment by Lyceion** [comment]
> I did that, it still gives the same error, very weird.

can you also try recompile osxinj & bootstrap for M1? 

Is there any errors while compiling? At least it should give something...

And i'm going to try your dylib right now...

**Comment by Lyceion** [comment]
The compiled one for M1 didn't worked for me (and it's very normal). But it should work for you. As i said before (you can search on google) they say it's about osxinj. I didn't looked to much on it so idk why it happens but, yeah. It's not about our cheat. Tried on (2020, 2019)

<img width="1788" alt="Ekran Resmi 2021-02-04 04 03 43" src="https://user-images.githubusercontent.com/21990827/106829982-367d9d80-669e-11eb-8a17-d1ecf944ddc9.png">

**Comment by Lyceion** [comment]
Can you see the ButOSX button on touchbar after you inject?

**Comment by jakepriddle** [comment]
<img width="1440" alt="Screen Shot 2021-02-03 at 8 38 18 PM" src="https://user-images.githubusercontent.com/50683048/106832514-d10abc00-665f-11eb-8f26-bd10a2f800df.png">
Ahh maybe the injector is the problem, I am unable to compile as arm64 though, I have to compile as x86_64, feel free to close the issue, I will just wait till you guys write one.

**Comment by Lyceion** [comment]
No problem. It'll be very hard to write an injector to the computer which we don't have but we'll gonna try.
Closing...

**Comment by Lyceion** [comment]
Hello again. Can you test with compiling https://github.com/Lyceion/CroXinj and using it with? (Plase compile both ButOSX and CroXinj for m1 and test like that. If it works, it'll be awesome.)

**Comment by jakepriddle** [comment]
Thank you, I will tonight or tomorrow:)

**Comment by jakepriddle** [comment]
Sadly it still doesn't compile for arm. I would be happy to talk further on another platform so we don't have to converse thourgh GitHub issues. Feel free to reach out to me on discord: ```jakep#8028``` :)
